### PR TITLE
add installation commands for osx-dev dependencies

### PR DESCRIPTION
**Pull request by merongivian**
this partially solves #190

### CODE REVIEW

**Comment by juniorz** [comment]
That are too many variables that should be resolved by the user. For example:

- Having `ports` or `fink` installed does not mean I want to install using them.
- The package names might be different across different package managers.
- The invocation not only varies on the app name. `port` requires `sudo`, `brew` discourages `sudo`.
- You might need to update the package manager metadata before installing, and again this is specific to the package manager. Ports has `port sync`, Homebrew has `brew update`, and so on.

So why not letting the user install it by himself/herself?

Providing this means we will have to maintain it, and I'm not comfortable with the effort to maintain all these moving parts versus the unclear benefit.

Having a docker image would provide more value, to the cost of making a lot of choices to the user (a specific linux distro, a specific distro version, a specific package manager, a specific version of each dependency, and so on). The ability to control the docker environment reduces the moving parts.

Note the files in `ci/install*` are supposed to be run in a controlled environment (Travis VMs).

`coyim` is very simple, and hacking on it requires some knowledge of GTK. If a contributor cant have a valid GTK installation on her/his system, it is unlikely the contributor will be able to hack on GTK.

**Comment by merongivian** [comment]
@juniorz part of the objective with my last PR's where to make it easier for any dev to start working/contributing on the project, or at least point out that there are still some issues (or at least i had) setting up the environment correctly before running the test suite. 

Aside from dependencies installation,  i still think there is room for improvement (perhaps this could be solved adding some more instructions in the CONTRIBUTING.md file). Take the `GOPATH` set up for example,  i thought there was an issue with a package i didn't have, but it turns out you have to tweak your go path in order to have the project correctly importing your files. I agree that the 'containerized' solution would solved both the deps/path issues i had, so if there is a Docker solution (or if i can help creating one :) ), let me know

**Comment by juniorz** [comment]
Making it easier is a great goal. I'm only concerned about the approach for the reasons I mentioned before.

> Take the GOPATH set up for example, i thought there was an issue with a package i didn't have, but it turns out you have to tweak your go path in order to have the project correctly importing your files.

There should be no special tweak necessary to make import works. If you have a working golang installation, which includes having a properly configured `GOPATH`, you should have it up and running with standard golang commands.

If there's any necessary tweak it is a bug. You should be able to start a fresh development environment by simply changing the `GOPATH`:

```
/tmp % export GOPATH="/tmp/coy-env"
/tmp % rm -rf $GOPATH
/tmp % go get -t github.com/twstrike/coyim/...
/tmp % cd $GOPATH/src/github.com/twstrike/coyim
[master] github.com/twstrike/coyim % go test ./...
?   	github.com/twstrike/coyim	[no test files]
ok  	github.com/twstrike/coyim/cli	0.015s
?   	github.com/twstrike/coyim/client	[no test files]
ok  	github.com/twstrike/coyim/config	2.759s
ok  	github.com/twstrike/coyim/config/importer	0.914s
?   	github.com/twstrike/coyim/event	[no test files]
ok  	github.com/twstrike/coyim/gui	0.245s
?   	github.com/twstrike/coyim/gui/definitions	[no test files]
?   	github.com/twstrike/coyim/i18n	[no test files]
ok  	github.com/twstrike/coyim/net	0.022s
?   	github.com/twstrike/coyim/net/nettest	[no test files]
ok  	github.com/twstrike/coyim/roster	0.023s
ok  	github.com/twstrike/coyim/sasl	0.014s
ok  	github.com/twstrike/coyim/sasl/digestmd5	0.011s
ok  	github.com/twstrike/coyim/sasl/plain	0.011s
ok  	github.com/twstrike/coyim/sasl/scram	0.023s
?   	github.com/twstrike/coyim/servers	[no test files]
ok  	github.com/twstrike/coyim/session	1.028s
ok  	github.com/twstrike/coyim/ui	0.011s
ok  	github.com/twstrike/coyim/xmpp	0.778s
```

**Comment by merongivian** [comment]
@juniorz you see, this is the 'tweak' part i was talking about:
```
/tmp % go get -t github.com/twstrike/coyim/...
```
you need to install coyim for make the `imports` work inside coyim:
```
import "github.com/twstrike/coyim/client"
```
@juniorz the `go get -t git...` make it work, i thought that my `GOPATH` was wrong also

**Comment by juniorz** [comment]
I see. However, this is not a tweak. This is how golang works.

Everything in go works on packages, and a package is defined by a directory inside `$GOPATH/src/yourpakage`.

You just need to have the `github.com/twstrike/coyim` package. `go get` gives you this for free, as a consequence of getting (or installing) the package.

Take a look at: http://dave.cheney.net/2014/12/01/five-suggestions-for-setting-up-a-go-project

**Pull request closed without merging**
