### PR TITLE
Added to/alphabetized Onion Server List - resolves #127

### LINKED ISSUE #127: Improve the list of hardcoded mapping between servers and hidden services
This is a split of #56

### PR DESCRIPTION
**Pull request by grayleonard**
Found by iterating through the xmpp.net server directory and some google searching.

### CODE REVIEW

**Comment by olabini** [comment]
Thanks, this is great - however, it would be good if you have references to where you got these, so we have some reasonable certainty that they are correct.

**Comment by grayleonard** [comment]
@olabini Added sources in e80adfd - let me know if that's sufficient.

**Comment by olabini** [comment]
The references are fine, but you removed dukgo.com, jabber.ccc.de and riseup.net.

**Comment by grayleonard** [comment]
I just repositioned them :-)

**Comment by olabini** [comment]
Ah, sorry, for some reason I missed them.

**Comment by olabini** [comment]
Thank you.

**Pull request merged**
