### PR TITLE
MakeFile fixes

### PR DESCRIPTION
**Pull request by merongivian**
This PR fixes the following problems i found while running the `make` command
* Fix the test suite locally (it gave me some errors since its not finding the url "github.com/strike/coyim..." on file imports)
* Include gtk installation command (for osx)

### CODE REVIEW

**Comment by tcz001** [comment]
Thanks for PR,
Besides the gtk+3 I guess we may need more toolkits like gettext and gnome-icon-theme for osx.

Golang don't suggest use a relative path, so we may keep the absolute one for now. You can make the repo in gopath as a workaround.

**Comment by merongivian** [comment]
@tcz001 how do you run your tests locally then? :open_mouth:  i got an error when running them because the github `import 'github.com...' ` returned me a not found error...

**Comment by tcz001** [comment]
probably the repo isn't in side gopath, usually we will make it in side of $GOPATH/src/ and create a symbolic link in anywhere we want to have a quicklink.

**Comment by tcz001** [comment]
I'd like to merge the first commit about Makefile, if you can make osx-deps not required by deps, because there are more than one way you can install gtk+3, if someone has a self-compiled latest version, we don't want to mess up his environment.

**Comment by merongivian** [comment]
@tcz001 do you want it to somehow check if you installed osx dependencies in other ways (macports, source, etc) , or just add it as a separate task for installing brew packages ?

**Comment by tcz001** [comment]
Sure, Thanks

**Comment by juniorz** [comment]
Also, take a look at https://github.com/twstrike/coyim/blob/master/CONTRIBUTING.md#getting-started

You can also see the dependencies we install on Mac in the file `ci/install-deps-osx`

**Comment by tcz001** [comment]
yeah I guess we need to move toolkit related scripts like ci/install-deps-osx into provisioning, can also try to make a linux/windows one sometime...

**Comment by merongivian** [comment]
@tcz001 @juniorz out of curiosity , i see that you are using docker for the main dmg installation, do you guys also use docker locally for dev ? if yes would be great to have instructions for those in the guideline, @juniorz thanks for pointing out `ci/install-deps-osx`, going to add those dependencies to the makefile

**Pull request closed without merging**
