### PR TITLE
Use github.com/mjibson/esc to embed UI definition files

### PR DESCRIPTION
**Pull request by juniorz**
We could use the same to embed other resources (like icons and gsettings).

cc/ @rosatolen and @yakiradixon

### CODE REVIEW

**Comment by rosatolen** [comment]
These changes to compress/gzip in golang are causing the build failures for different golang versions:
https://beta.golang.org/doc/go1.8#compress_gzip

Otherwise, coyim windows are appearing correctly. 

I believe if we all migrate to go 1.8, then we will not need to worry about these build errors affecting commits to master.

**Comment by olabini** [comment]
We can't all migrate to 1.8 - we need to stay compatible back to 1.6 in my opinion,

**Comment by juniorz** [comment]
+1

**Comment by rosatolen** [comment]
To keep compatibility with Golang 1.6, compression has been removed from this pull request.

**Comment by rosatolen** [comment]
We are considering using this method for embedding images used in the SMPUI branch. Are there any additional objections to including the esc tool?

**Comment by rosatolen** [comment]
We have checked that there are no inconsistencies when running the reproducible build and no failures when creating a dmg. :D

**Pull request merged**
