### PR TITLE
Single window

### PR DESCRIPTION
**Pull request by brl**
I implemented an optional single window UI layout which you can enable by passing a command line flag:

    coyim -single

As you can imagine, I needed to do some refactoring:

- Separated conversation window into the window and the internal component (conversationPane)
- Created an interface conversationView to the public API of ConversationWindow
- Created a conversationView implementation for the single window UI (conversationStackItem)
- Pushed a horizontal box into the top level of Main.xml

I hope I didn't break anything!

The main implementation of the single window UI is in:

    gui/unified.go
    gui/definitions/UnifiedLayout.xml

### CODE REVIEW

**Comment by olabini** [comment]
Hey, this looks great, thank you! I'm slightly worried taking ownership of it, but that might be OK. 
I do have a few comments:
- I'm not a huge fan of using a command line flag for this, and especially not -single (since we already have a -multi flag with a different meaning). I think the better approach would be using a configuration file item. Would that be possible, and if so, would it be possible to switch over between the modes while running?
- Not sure why Show and SetEnabled are external while the rest of the functions in the conversationView interface are internal. Can we just make them all internal?
- It seems gui/unified.go wasn't saved with goformat/goimports run on the latest commits.

**Comment by brl** [comment]
- The command line flag isn't meant to be permanent.  For now it's a convenient way to demonstrate the feature without otherwise changing anything about how Coy works (in case you hate it :).  It also allows us to turn it on by default in Subgraph OS so that we can get it well tested.

- It should be possible to switch the layouts while running either by reparenting conversationPane (maybe this doesn't work on every platform?) or by just moving the GtkTextBuffer into a new view.
- Ok, I changed Show and SetEnabled to unexported, these names were inherited from original implementation.

- Looks fmt to me, what's the problem?

**Comment by olabini** [comment]
OK, great. The fmt issue was in the call to builder.GetItems, but it might be one of those cases where it doesn't fmt correctly.

Assuming we change the command line flag to something else later, should be good. Let me try it out.

**Comment by olabini** [comment]
Hmm, lint isn't happy. I can fix that though.

**Comment by olabini** [comment]
OK, I will merge it - there are two things that I think would be good
First, if you have an info bar warning about no verification of identity, and then open another conversation, and move back, the text inside the verification bar will be selected.
Second, if you have more than one account, it would be great to see both the account name and the peer name in the right pane.

**Comment by olabini** [comment]
Thank you!

**Comment by brl** [comment]
There are still a few glitches that I'm going to work on today, but thanks for merging so I don't get too far out of sync.  There is also a similar problem if you have some text in a conversation GtkEntry and you switch back to that conversation all the text will be highlighted.

Not sure what the correct workflow is because I haven't used Github pull requests very much but I'm going to keep working in this branch and then later submit another pull request on it I guess.

**Comment by olabini** [comment]
OK, sounds good. We won't touch those parts of CoyIM very much at the moment, so it should be safe for you to work in this manner.

**Comment by olabini** [comment]
If it gets too annoying we'll add you to the repo instead.

**Pull request merged**
